// AUTO-GENERATED by scripts/gen-content-meta.mjs — do not edit by hand.
// Re-run `node scripts/gen-content-meta.mjs` after changing a post's `meta`
// (this also runs automatically as the first step of `npm run build`).
import type { CaseStudyMeta } from './registry';

export const caseStudyMetaEntries: { path: string; meta: CaseStudyMeta }[] = [
  {
    "path": "./aladeen.mdx",
    "meta": {
      "slug": "aladeen",
      "title": "Aladeen: An Observability Layer for Agent CLIs | Naqeebali Shamsi",
      "description": "A read-only TypeScript pipeline that normalizes five agent-CLI log stores (JSONL and SQLite) onto one Zod schema waist, content-addresses runs by a failure fingerprint, and mines remedies without ever running the agent.",
      "headline": "Reading the Black Box: An Observability Layer for Agent CLIs",
      "deck": "Five agent CLIs, two storage shapes, one schema waist, and a remedy engine whose cheapest path through the code is \"I have nothing comparable.\"",
      "datePublished": "2026-06-08",
      "dateModified": "2026-06-08",
      "tags": [
        "TypeScript",
        "MCP",
        "observability",
        "AI agents",
        "Zod",
        "Node.js",
        "system design"
      ],
      "metrics": [
        {
          "value": "5",
          "label": "Log stores → 1 schema"
        },
        {
          "value": "9",
          "label": "Event kinds (sum type)"
        },
        {
          "value": "199",
          "label": "Real sessions mined"
        },
        {
          "value": "42",
          "label": "Fingerprint buckets"
        },
        {
          "value": "248",
          "label": "Test cases"
        }
      ],
      "links": [
        {
          "label": "npm",
          "href": "https://www.npmjs.com/package/aladeen"
        },
        {
          "label": "GitHub",
          "href": "https://github.com/naqeebali-shamsi/Aladeen"
        }
      ],
      "faq": [
        {
          "q": "Why not just use an orchestrator like Conductor or Vibe Kanban?",
          "a": "Those drive the agent. Aladeen does the opposite: it never runs your agent, it reads the logs your agent already writes to disk and mines them for recurring failure shapes. The orchestrator category is saturated; observability for CLI-based agents was essentially empty. Aladeen actually started as an orchestrator and was deliberately demoted. The runner survives only because its own execution traces are a fifth ingestible source, which closes an observability loop on the engine itself."
        },
        {
          "q": "How do you normalize a JSONL log and a SQLite database into the same schema?",
          "a": "A Zod SessionTrace, a discriminated union over 9 event kinds with a monotonic per-session seq and a SourceRef back-pointer on every event, is the fixed waist every ingester targets. The Claude Code ingester pairs tool_use to tool_result across separate JSONL lines via a callIndex map; the opencode ingester reads a relational SQLite store where a call and its result share one row, and splits it into two events, emitting the result only when the row status is terminal. Every trace is safeParse-d at the boundary, so a schema regression fails at the parser, not at three consumers downstream. Source-aware code lives strictly upstream of that parse; everything below it is source-blind."
        },
        {
          "q": "Why read SQLite through a subprocess instead of a native module?",
          "a": "To keep the core observability path pure-JS with zero native dependencies, so `npx aladeen report` runs anywhere Node 20+ does with no compile step: the dominant constraint for a zero-budget solo CLI. opencode's DB is read via a `sqlite3 -readonly -json` subprocess behind an injectable SqlExec seam, which makes it mockable in tests and swappable for better-sqlite3 later. The cost is a runtime dependency (sqlite3 on PATH, checked at preflight) and string-interpolated SQL, since the CLI has no parameter binding, a small injection surface mitigated by quoting ids that are bounded to ses_/msg_ alphanumerics."
        },
        {
          "q": "How does the remedy engine find a session that solved a failure when the fingerprint bakes in the outcome?",
          "a": "It can't use a same-bucket lookup: because outcome is an input to the fingerprint, a failing bucket contains zero successful sessions by construction. So the remedy engine joins across fingerprints on a sub-signature of (agent + sorted error classes) that deliberately drops outcome, failure-rate, and edit-loops, then keeps any completed session sharing that signature as a resolved sibling. It trades precision for recall on purpose, which is why the result is labeled a lead, not a fix, and prints its nFailed/nResolved denominators instead of a confidence score."
        },
        {
          "q": "What stops the remedy engine from overclaiming on thin data?",
          "a": "Four hard short-circuit gates and per-tier templated language. A non-failing bucket returns none with nFailed=0; an empty sub-signature suppresses to none; zero resolved siblings returns none; medium requires at least 3 resolved siblings or it downgrades to low. The guardrail string is templated per tier so the literal word \"fix\" can only appear on the rule-encoded tier. A unit test asserts the count of \"fix\" equals the count of \"not a fix\" in the lower-tier markdown, which mechanically proves you cannot upgrade a suggestion by tone. On a 199-session store where most buckets are size 1, the honest answer is usually \"I have nothing comparable.\""
        },
        {
          "q": "How does a running agent query this mid-session?",
          "a": "Aladeen ships an MCP server (aladeen-mcp) over stdio with three read-only tools and two resources, wired in with one .mcp.json entry. Each tool returns both human-readable markdown and a machine-actionable structuredContent payload (tier, sub-signature, denominators, rule citations, change-shaped evidence) so a calling agent acts on the data without scraping prose, and isError is wired to empty result sets as a real tool-error contract. It never touches the network and never launches an agent CLI; the connected agent stays the actor."
        }
      ]
    }
  },
  {
    "path": "./audex.mdx",
    "meta": {
      "slug": "audex",
      "title": "Audex: A Byte-Deterministic Excel-to-PDF Audit Engine | Naqeebali Shamsi",
      "description": "Audex: an offline Electron app (vanilla JS, pdfmake) that compiles a fixed-structure Excel audit workbook into a byte-identical PDF statement set, locked by a golden SHA256: a pure pipeline, a DOM-free layout engine, and a framework-agnostic command/undo editing core.",
      "headline": "Same Workbook In, Same PDF Out: Engineering Determinism End to End",
      "deck": "A layout problem wearing a document problem’s clothes. The adversary was nondeterminism, and the deliverable had to match to the byte on every run, including after an operator edits the notes.",
      "datePublished": "2026-06-08",
      "dateModified": "2026-06-08",
      "tags": [
        "Electron",
        "JavaScript",
        "pdfmake",
        "determinism",
        "system design",
        "concurrency",
        "offline-first",
        "audit software"
      ],
      "metrics": [
        {
          "value": "byte-identical",
          "label": "Output, pinned to a golden SHA256"
        },
        {
          "value": "3-pass",
          "label": "Pure DOM-free layout engine"
        },
        {
          "value": "17",
          "label": "IPC channels (pure DI factory)"
        },
        {
          "value": "181 / 573",
          "label": "Tests / assertions (node:test)"
        },
        {
          "value": "O(1) clock",
          "label": "Wall-clock inputs frozen to one constant"
        },
        {
          "value": "4",
          "label": "Statement types parsed by an FSM"
        }
      ],
      "links": [
        {
          "label": "Microsoft Store",
          "href": "https://apps.microsoft.com/detail/9P87TFB7D3TD"
        }
      ],
      "faq": [
        {
          "q": "What is Audex?",
          "a": "Audex is an offline Electron desktop app (vanilla-JS renderer, Node/CommonJS main, pdfmake) that compiles a firm's fixed-structure Excel audit workbook into a byte-deterministic A4-portrait PDF statement set: Financial Position, Profit or Loss / OCI, Cash Flows, Changes in Equity, plus a cross-referenced Notes appendix. It runs fully offline on Windows and ships through the Microsoft Store. Its defining property is determinism: every layer on the bytes path is a pure function of its input, the single wall-clock input is frozen, and the whole output is pinned to a committed golden SHA256."
        },
        {
          "q": "How do you make PDF output byte-for-byte deterministic?",
          "a": "Kill the one nondeterministic input and make everything else a pure function. PDFs stamp wall-clock time into /CreationDate and /ModDate, so I freeze both to 2000-01-01T00:00:00Z; the parser, the layout engine, and the generator never read a clock, DOM, or canvas. Then the whole statements-plus-notes output is locked to a committed golden SHA256 (fb46bef2…) that only an explicit UPDATE_GOLDEN=1 can rewrite. A missing golden is a hard failure, never a silent self-rebaseline."
        },
        {
          "q": "How does determinism survive an operator editing the notes?",
          "a": "The editing core holds CANONICAL note JSON, not the transient ProseMirror editor model, so an unedited note is never re-serialized. A two-tier serializer returns clean blocks byte-identical (a structuredClone of the original, because ProseMirror JSON is lossy on bare-string vs {text} segments) and re-serializes only edited blocks into one idempotent canonical normal form. An unedited note therefore can't perturb the golden hash."
        },
        {
          "q": "How do you lay out text without a browser or canvas to measure it?",
          "a": "Width comes from a pure character-class estimator seeded with the font's real glyph advances at 2048 units-per-em: digit = 1024/2048 (0.500), lowercase = 0.459, with per-class bold multipliers and an 8% margin biased one-directionally toward over-estimation. That 8% bias converts a bounded per-glyph error into a hard no-overflow invariant (a clipped audit figure is unshippable, a slightly wide column is fine), and the purity is exactly what keeps the 3-pass layout engine pure and the golden stable."
        },
        {
          "q": "How do operator edits reach the PDF safely with no database and an untrusted renderer?",
          "a": "A per-(client,period) JSON 'material bank' written atomically (tmp → fsync → .bak → rename), serialized per-ref behind a tail-chained promise lock, carrying a monotonic generation counter computed from the persisted value. Export is send-and-verify: it re-derives client and period server-side, rejects any mismatch the renderer claims, does ONE bank read shared by both the lost-write generation guard and the notes payload (no TOCTOU), and renders only notes it read itself."
        },
        {
          "q": "Why is the note schema the security boundary instead of HTML sanitization?",
          "a": "There is no HTML sink to sanitize. Operator rich text is stored as a closed grammar, not markup. So two closed grammars ARE the boundary, with deliberately different verbs: editor-schema.js validates-and-REJECTS at the ProseMirror seam, and content-model.js coerces-and-DROPS malformed rich text before disk. Both are own-property-hardened with Object.hasOwn / Reflect.ownKeys, so __proto__ and constructor are unknown types rather than truthy members, killing prototype pollution at the door."
        }
      ]
    }
  },
  {
    "path": "./intellifill.mdx",
    "meta": {
      "slug": "intellifill",
      "title": "IntelliFill: Multi-Agent LLM Pipeline for Document Extraction | Naqeebali Shamsi",
      "description": "A TypeScript LangGraph multi-agent pipeline that auto-fills government PDFs via a confidence-weighted LLM+regex merge, ICAO-9303 MRZ checksums, and a per-provider LLM circuit breaker.",
      "headline": "Earning the Right to Write a Passport Number into a Legal Form",
      "deck": "Five specialized agents on a LangGraph StateGraph, two extractors reconciled per field, and a confidence score honest enough to say \"I am not sure\", retrofitted behind seven flags onto a live PII pipeline.",
      "datePublished": "2026-06-08",
      "dateModified": "2026-06-08",
      "tags": [
        "TypeScript",
        "LangGraph",
        "system design",
        "LLM",
        "OCR",
        "Prisma",
        "multi-agent",
        "distributed systems"
      ],
      "metrics": [
        {
          "value": "5",
          "label": "Specialized agents on one StateGraph"
        },
        {
          "value": "3",
          "label": "LLM providers behind a circuit breaker"
        },
        {
          "value": "274",
          "label": "Agent/workflow unit tests (measured, LLM mocked)"
        },
        {
          "value": "38",
          "label": "Prisma models / 13 migrations"
        },
        {
          "value": "85",
          "label": "Vision confidence cap (heuristic, by choice)"
        }
      ],
      "links": [
        {
          "label": "GitHub",
          "href": "https://github.com/naqeebali-shamsi/portfolio"
        }
      ],
      "faq": [
        {
          "q": "Why run both an LLM and a regex extractor on every document instead of trusting the LLM?",
          "a": "Because there is no ground truth at inference time, and agreement between two independent extractors is the cheapest signal for catching a confident-but-wrong value. mergeExtractionResults() reconciles them field by field: a Levenshtein-gated agreement (>0.85 similarity) earns a +10 confidence boost on the LLM field; on a close disagreement (confidences within 10 points) the pattern value is discounted 0.85x so the LLM wins the tie; otherwise the higher confidence wins and a null source defers to the non-null one. Regex contributes precision on structured IDs (the Emirates ID 784-YYYY-XXXXXXX-X shape) that the LLM lacks. The cost is real: two extractors plus up to two self-correction passes multiply latency and spend, and the merge constants are hand-tuned, not learned."
        },
        {
          "q": "How does it catch a passport number that is plausible but wrong?",
          "a": "The Machine-Readable Zone encodes its own check digits, so a plausible-but-wrong value fails arithmetic even when it looks right. qaAgent.ts implements ICAO-9303 TD3: mrzCheckDigit() applies the repeating 7-3-1 weighting mod 10, and validateMrzLine2() recomputes the passport-number (index 9), date-of-birth (index 19), expiry (index 27), and composite (index 43) check digits at exact offsets on the 44-character line. Then crossValidateMrzFields() compares the MRZ-decoded passport number against the separately extracted field and flags a mismatch for human review. Honest failure mode: the checksum validator fails loudly on a malformed line (a non-44-char MRZ returns valid:false), but the cross-check is the lenient one: crossValidateMrzFields() returns valid:true and skips when the MRZ isn't a clean 44 chars, so the one region it leans on is trusted to have OCR'd correctly."
        },
        {
          "q": "What happens when the primary LLM provider rate-limits or goes down?",
          "a": "llmClient.ts fails over in priority order Gemini -> Claude -> OpenAI behind a per-provider CircuitBreaker that opens after 3 failures and half-opens after a 60-second reset; generate() throws only when every available provider is exhausted. Concurrency is bounded independently by a hand-rolled Semaphore(5) on Gemini calls, and each SDK is lazy-imported so an unused provider never loads. The breaker is deliberately lenient: half-open admits all requests in the reset window (no single-probe gate) and any one success deletes the failure count. It is also process-local, so global health across multiple workers is not coordinated."
        },
        {
          "q": "How do you ship a new LLM pipeline onto a live production PII flow without a big-bang cutover?",
          "a": "You feature-flag everything and design for a staged rollout. Seven env-var flags gate every AI capability (instant rollback, no deploy), each job carries isShadowMode and an abTestVariant, and the Prisma schema has a ProcessingComparison table (fieldDiff, matchingFieldsCount, accuracyDelta, winner) plus AgentMetrics and UserFeedback, read by an admin accuracy dashboard. Honest scope: the read/dashboard side is built but the write/measurement path is not. No committed code runs the legacy pipeline in shadow, diffs the fields, or writes a comparison row. So the apparatus to measure non-regression exists as schema and read surface; the loop is not yet closed."
        },
        {
          "q": "Why a LangGraph StateGraph instead of a plain async function with try/catch and retries?",
          "a": "Because error recovery has to route backward. When QA fails, the pipeline branches to a recovery node that classifies the failure into one of nine categories and routes back to extract or classify, or escalates to a human, capped at 3 retries under a 5-minute Promise.race. Expressing that as conditional graph edges (routeAfterQA, routeAfterErrorRecovery) keeps the control flow legible where nested try/catch with manual counters would tangle. The cost: graph.compile() is currently called with no checkpointer, so the graph is in-memory and not resumable. An interrupted run restarts from scratch on BullMQ retry, and the MultiAgentCheckpoint table is never written. Resilience comes from BullMQ (3 attempts, a 10-minute lock with 5-minute renew) plus the in-graph recovery loop, not from LangGraph state persistence."
        }
      ]
    }
  },
  {
    "path": "./mecanum.mdx",
    "meta": {
      "slug": "mecanum",
      "title": "Mecanum: Two ORMs on One Postgres, Bilingual RTL on Next.js 16 | Naqeebali Shamsi",
      "description": "How I designed Mecanum: a bilingual EN/AR (full RTL) lead-gen site on Next.js 16 where Payload CMS and Prisma share one Postgres via disjoint schemas, with a persist-then-notify write path and authorization pushed into SQL.",
      "headline": "The Star Rating That Read Backwards: System Design for a Bilingual Lead-Gen Site",
      "deck": "No cart, no checkout, no SKU table. Two ORMs on one Postgres, a system-of-record write path, and authorization compiled into a WHERE clause: in two languages and both directions.",
      "datePublished": "2026-06-08",
      "dateModified": "2026-06-08",
      "tags": [
        "Next.js 16",
        "Arabic RTL",
        "Payload CMS",
        "Prisma",
        "Postgres",
        "system design",
        "Zod",
        "idempotency"
      ],
      "metrics": [
        {
          "value": "2",
          "label": "ORMs, disjoint schemas, one Postgres"
        },
        {
          "value": "1",
          "label": "pg.Pool singleton, guarded against fan-out"
        },
        {
          "value": "2",
          "label": "write paths (1 idempotent, 1 not, by design)"
        },
        {
          "value": "24h",
          "label": "ISR invalidation on Google reviews"
        },
        {
          "value": "4.3M",
          "label": "base64-char cap = edge load-shed"
        }
      ],
      "links": [
        {
          "label": "Live",
          "href": "https://mecanum.ae"
        }
      ],
      "faq": [
        {
          "q": "Can you really run Payload CMS and Prisma against the same PostgreSQL database?",
          "a": "Yes, if the schemas are disjoint. Payload's postgres adapter is pinned to schemaName: 'payload' so every CMS table is DDL-scoped into that namespace; Prisma's models carry no @@schema and land in public. One DATABASE_URL, two independent migration ledgers, and collision-freedom is a property of namespace disjointness, not luck. The cost is structural: a Prisma Contact can never be SQL-JOINed to a Payload Post, accepted to keep the conversion path decoupled from CMS schema churn."
        },
        {
          "q": "How do you stop Arabic RTL from reversing numbers, ratings, and phone numbers?",
          "a": "Wrap every Latin-ordered run in <bdi dir=\"ltr\"> to force an isolated left-to-right Unicode embedding inside the RTL document. There is no global fix: each Latin island inside an RTL flow (a star rating, a \"+\" suffix, a VIN, a phone number) needs its own bidi isolate, because the bidirectional algorithm reorders at the run level. The bugs are invisible in English and only surface when you test in Arabic."
        },
        {
          "q": "Why persist the lead before sending the notification email, and what is the durability guarantee?",
          "a": "Because the Postgres row is the system of record and the email is a best-effort projection. POST /api/contact awaits prisma.contact.create first (the commit point), then awaits the Resend send but inspects its Result, logs {reason, contactId} on failure, and returns 201 regardless. The invariant is one-directional: a 201 implies a durable Contact row, never the reverse. So a Resend outage degrades to a recoverable row, not a lost customer."
        },
        {
          "q": "Is the contact endpoint idempotent? What about newsletter?",
          "a": "No and yes, deliberately. Newsletter subscribe is idempotent: findUnique on a @unique email returns 200 \"already subscribed\" (not 409), with the unique constraint as the real race guard, so re-submission is a safe no-op. The contact POST is NOT idempotent (every accepted call inserts a row), which is why the browser retry client only retries on 5xx/network errors and never on 4xx, though that narrows the double-insert window rather than closing it (there is no request-id dedupe)."
        },
        {
          "q": "How is scheduled blog publishing enforced: in app code or in the database?",
          "a": "In the database, as a query predicate. Payload Posts `read` access returns a Where object {and:[{status:{equals:'published'}},{publishedAt:{less_than_equal: new Date().toISOString()}}]} for anonymous requests instead of a boolean, and Payload composes it into the underlying SQL WHERE. Drafts and future-dated posts are unfetchable at the query layer, so a post with a future publishedAt is simply invisible until wall-clock time passes it: row-level access control, not an app-code filter."
        },
        {
          "q": "Why hand-roll i18n instead of using next-intl or i18next?",
          "a": "Two locales and a fixed marketing surface do not justify a runtime dependency. Mecanum uses a single `as const` EN+AR tree plus a DeepReadonlyToMutable mapped type, so a missing or misspelled key (t.stats.projects) is a TypeScript error and EN/AR are forced to the same shape: full key safety, zero bytes of runtime i18n machinery. The real i18n difficulty was bidi layout, which no string library solves anyway."
        }
      ]
    }
  }
];
