# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Netlify workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    defaults:
      run:
        working-directory: /

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Create .env file
      run: |
        echo "GITHUB_USERNAME=naqeebali-shamsi" > $GITHUB_WORKSPACE/.env
        echo "USE_GITHUB_DATA=true" >> $GITHUB_WORKSPACE/.env
        echo "MEDIUM_USERNAME=naqeebali-shamsi" >> $GITHUB_WORKSPACE/.env
        
    - name: Install dependencies
      run: npm i --legacy-peer-deps

    - name: Build
      run: CI=false npm run build --if-present

    - name: Netlify Deploy
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      run: |
        netlify deploy --dir "build" --prod --auth "$NETLIFY_AUTH_TOKEN" --site "$NETLIFY_SITE_ID"
